# Generated by Django 4.2.2 on 2023-06-08 17:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0002_blog_certificate_contactprofile_media_skill_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AvatarFeed",
            fields=[
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_question_message",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("video_path", models.CharField(blank=True, max_length=300, null=True)),
                (
                    "video_changed",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("first_video", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
