# Generated by Django 4.2.2 on 2023-06-09 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0003_avatarfeed"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Blog",
        ),
        migrations.DeleteModel(
            name="Testimonial",
        ),
    ]
