# Generated by Django 4.2.2 on 2023-06-10 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolio", "0004_delete_blog_delete_testimonial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="avatarfeed",
            name="user_question_message",
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
